version: 2.0

references:
  # Default container configuration
  #
  container_config: &container_config
    docker:
      - image: circleci/php:7.2
    environment:
      - WP_CORE_DIR: /tmp/wordpress/
      - WP_TESTS_DIR: /tmp/wordpress-tests-lib
      - WP_VERSION: latest
    working_directory: ~/passwords-evolved

  workspace_root: &workspace_root
    /tmp

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  copy_vendor: &copy_vendor
    run:
      name: Copy vendor directory
      command: cp -R /tmp/vendor .

  # Default configuration for all phpunit testing jobs
  #
  test_job: &test_job
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *copy_vendor
      - run:
          name: Run PHP unit tests
          command: vendor/bin/phpunit

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: composer install -n -o
      - run:
          name: Install WordPress
          command: bash tests/bin/install-wp.sh $WP_VERSION
      - persist_to_workspace:
          root: .
          paths:
            - vendor
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - wordpress

  code_quality:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *copy_vendor
      - run:
          name: Run code quality tests
          command: vendor/bin/grumphp run --testsuite=code_quality

  test_php72:
    <<: *test_job
    docker:
      - image: circleci/php:7.2

  test_php71:
    <<: *test_job
    docker:
      - image: circleci/php:7.1

  test_php70:
    <<: *test_job
    docker:
      - image: circleci/php:7.0

  test_php56:
    <<: *test_job
    docker:
      - image: circleci/php:5.6

  test_php55:
    <<: *test_job
    docker:
      - image: vandries/phpenv:5.5

  test_php54:
    <<: *test_job
    docker:
      - image: vandries/phpenv:5.4

  deploy:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *copy_vendor
      - run:
          name: Install subversion
          command: sudo apt-get install subversion
      - run:
          name: Deploy new version to WordPress plugin directory
          command: .circleci/deploy.sh

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - code_quality:
          requires:
            - build
      - test_php72:
          requires:
            - code_quality
      - test_php71:
          requires:
            - code_quality
      - test_php70:
          requires:
            - code_quality
      - test_php56:
          requires:
            - code_quality
      - test_php55:
          requires:
            - code_quality
      - test_php54:
          requires:
            - code_quality
      - deploy:
          requires:
            - test_php72
            - test_php71
            - test_php70
            - test_php56
            - test_php55
            - test_php54